_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 71
                - 83
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 71
                - 83
            "3":
                - 13
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.9
            "6": 4.51.0
            "8":
                - 3
                - 5
            "12": 0.19.9
            "13": windows-amd64
